### ISSUE TITLE
`MaterialBuilder` を直接元素の登録に使うのは不適切ではないか

### ISSUE THREAD

**Issue by kobi32768** [Hiiragi283/RagiMaterials#2]
`MaterialBuilder` はその他の `-Builder` の継承元となっているようだが、それを直接元素の登録に使うのはやや不適切なのではないかと感じる。

https://github.com/Hiiragi283/RagiMaterials/blob/0868eb0cb504ee925322d045a28baabdc84ce6e0/src/main/kotlin/hiiragi283/ragi_materials/material/MaterialBuilder.kt#L9

https://github.com/Hiiragi283/RagiMaterials/blob/0868eb0cb504ee925322d045a28baabdc84ce6e0/src/main/kotlin/hiiragi283/ragi_materials/material/MaterialRegistry.kt#L16

**Comment by Hiiragi283** [comment]
[80a754f](https://github.com/Hiiragi283/RagiMaterials/commit/80a754f2097f3e2a2b050c35ec88bc757ba27683)にて修正しました
