### ISSUE TITLE
[バグ] RagiMaterialのみ [0.6.0b]

### ISSUE THREAD

**Issue by MrKono** [Hiiragi283/RagiMaterials#3]
### RagiMaterialsのバージョン

v0.6.0b

### サーバー/クライアント

client

### クラッシュの再現方法

1. インストール

### 本来の挙動

**1.** I.C.R.Cは搬入されたアイテムがレシピに一致する場合1秒毎にレシピを実行する
**2.** Stone MillでCruhsed Gold Oreを処理するとgold dustが入手できる
**3.** ToolTip曰くStone Mill / Laboratory Tableに右クリでアイテムを搬入できる
**4.** 回収したBlazing Forgeは再設置をしても正しく描画される
**5.** Spodumeneの名称が与えられている
**6.** Chlorine Full Bottleに元素記号とモル質量も与えられている 

### 実際の挙動

**1.** I.C.R.Cが動かない
**2.** Stone MillでCruhsed Gold Oreを処理すると無が採れる (Fig. 1)
**3.** Stone Mill / Laboratory Tableに右クリでアイテムを搬入できない (ToolTip間違い?)
**4.** 回収したBlazing Forgeを設置するとブレイズが描画されない (アイテム状態では描画される) (Fig. 2)
**5.** Spodumeneに名前が与えられていない (Fig. 3)
**6.** Chlorine Full Bottleに物質名しか与えられていない (Fig.4)

### 追加の説明

Fig.1
![2023-03-25_12 48 58](https://user-images.githubusercontent.com/90126004/227696638-2d257735-db8f-4843-b940-36a643dc604b.png)
Fig .2
![2023-03-25_12 52 05](https://user-images.githubusercontent.com/90126004/227696681-4e8f5980-8113-44c5-982a-2e824b70bc15.png)
Fig. 3
![2023-03-25_13 46 23](https://user-images.githubusercontent.com/90126004/227696695-1b4c7256-b556-4247-bbd1-250dc555acd1.png)
Fig. 4
![2023-03-25_13 46 25](https://user-images.githubusercontent.com/90126004/227696700-9204052d-1105-4339-913e-5ab9bd083ee0.png)

(再起動後も確認)

**Comment by Hiiragi283** [comment]
ご報告ありがとうございます。

1. ICRCは電源の供給も必要になります。
2. 現在Goldの素材登録がなされていないため、暫定的にEMPTYを指定しています。
3. GUI追加の際にツールチップの書き換えを忘れていました。修正させていただきます。
4. 未知の不具合のため解明には時間がかかる恐れがあります。
5. 修正させていただきます。
6. 修正させていただきます。

**Comment by MrKono** [comment]
1.について
Cyclicの無線設備で給電した場合のみ遭遇するようです

**Comment by Hiiragi283** [comment]
以下の問題を修正しました。
3. 9e6fcc9
4. fc518e3
5. 9e6fcc9
6. d9e1751

**Comment by Hiiragi283** [comment]
v0.6.1bを公開したためcloseさせていただきます。
