### ISSUE TITLE
CraftTweaker未導入時にクラッシュする

### ISSUE THREAD

**Issue by inaka-yuk** [Hiiragi283/RagiMaterials#4]
### RagiMaterialsのバージョン

v0.6.0

### サーバー/クライアント

クライアント

### クラッシュの再現方法

1. インスタンスのmodsフォルダにRagiMaterials v0.6.0と前提であるForgelinを入れる
2. インスタンスを起動する
3. 起動中にクラッシュする

### クラッシュレポートの貼り付け場所

https://pastebin.com/r6aq8MK2

**Comment by Hiiragi283** [comment]
確認したところ、CraftTweakerの有無によらずBracketHandler（<minecraft:iron_ingot>のように「<>」でオブジェクトを取り回す設計）の登録を行なっているのが原因と判明しました。
近日中に修正版を配布します。

**Comment by Hiiragi283** [comment]
コミット 236fccd にて修正しました。
